# Form implementation generated from reading ui file 'BaigiamasisDarbas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 284)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nuoroda = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nuoroda.setGeometry(QtCore.QRect(40, 20, 421, 31))
        self.nuoroda.setObjectName("nuoroda")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 401, 21))
        self.label.setObjectName("label")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(470, 20, 81, 31))
        self.mygtukas.setObjectName("mygtukas")
        self.komentaras = QtWidgets.QLabel(parent=self.centralwidget)
        self.komentaras.setGeometry(QtCore.QRect(40, 60, 631, 291))
        self.komentaras.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.komentaras.setText("")
        self.komentaras.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.komentaras.setObjectName("komentaras")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Įveskite tinklalapio nuorodą"))
        self.mygtukas.setText(_translate("MainWindow", "Paspausti"))
