# Form implementation generated from reading ui file 'skelbimai.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 479)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nuoroda = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nuoroda.setGeometry(QtCore.QRect(160, 160, 421, 31))
        self.nuoroda.setObjectName("nuoroda")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 130, 401, 21))
        self.label.setObjectName("label")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(340, 200, 75, 24))
        self.mygtukas.setObjectName("mygtukas")
        self.komentaras = QtWidgets.QLabel(parent=self.centralwidget)
        self.komentaras.setGeometry(QtCore.QRect(170, 240, 411, 81))
        self.komentaras.setText("")
        self.komentaras.setObjectName("komentaras")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Įveskite tinklalapio nuorodą"))
        self.mygtukas.setText(_translate("MainWindow", "Paspausti"))
