# Form implementation generated from reading ui file 'slaptazodis.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 458)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.elpastas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.elpastas.setGeometry(QtCore.QRect(170, 100, 271, 31))
        self.elpastas.setObjectName("elpastas")
        self.slaptazodis = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.slaptazodis.setGeometry(QtCore.QRect(170, 160, 271, 31))
        self.slaptazodis.setObjectName("slaptazodis")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 80, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 140, 201, 16))
        self.label_2.setObjectName("label_2")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(250, 200, 91, 31))
        self.mygtukas.setObjectName("mygtukas")
        self.Komentaras = QtWidgets.QLabel(parent=self.centralwidget)
        self.Komentaras.setGeometry(QtCore.QRect(170, 240, 271, 101))
        self.Komentaras.setText("")
        self.Komentaras.setObjectName("Komentaras")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Įveskite el. paštą"))
        self.label_2.setText(_translate("MainWindow", "Įveskite slaptažodį"))
        self.mygtukas.setText(_translate("MainWindow", "Prisijungti"))
