# Form implementation generated from reading ui file 'uzduotis.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 265)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mygtukas_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas_minus.setGeometry(QtCore.QRect(120, 60, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.mygtukas_minus.setFont(font)
        self.mygtukas_minus.setObjectName("mygtukas_minus")
        self.mygtukas_plius = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas_plius.setGeometry(QtCore.QRect(290, 60, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.mygtukas_plius.setFont(font)
        self.mygtukas_plius.setObjectName("mygtukas_plius")
        self.laukelis = QtWidgets.QLabel(parent=self.centralwidget)
        self.laukelis.setGeometry(QtCore.QRect(228, 65, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.laukelis.setFont(font)
        self.laukelis.setObjectName("laukelis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mygtukas_minus.setText(_translate("MainWindow", "Minus"))
        self.mygtukas_plius.setText(_translate("MainWindow", "Plius"))
        self.laukelis.setText(_translate("MainWindow", "1"))
