# Form implementation generated from reading ui file 'vardas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 438)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vardas = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vardas.setGeometry(QtCore.QRect(90, 110, 301, 31))
        self.vardas.setObjectName("vardas")
        self.mygtukas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mygtukas.setGeometry(QtCore.QRect(190, 280, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.mygtukas.setFont(font)
        self.mygtukas.setObjectName("mygtukas")
        self.pavarde = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pavarde.setGeometry(QtCore.QRect(90, 170, 301, 31))
        self.pavarde.setObjectName("pavarde")
        self.amzius = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amzius.setGeometry(QtCore.QRect(90, 230, 301, 31))
        self.amzius.setObjectName("amzius")
        self.pasisveikinimas = QtWidgets.QLabel(parent=self.centralwidget)
        self.pasisveikinimas.setGeometry(QtCore.QRect(90, 90, 271, 21))
        self.pasisveikinimas.setObjectName("pasisveikinimas")
        self.pasisveikinimas_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.pasisveikinimas_2.setGeometry(QtCore.QRect(90, 150, 271, 20))
        self.pasisveikinimas_2.setObjectName("pasisveikinimas_2")
        self.pasisveikinimas_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.pasisveikinimas_3.setGeometry(QtCore.QRect(90, 210, 271, 20))
        self.pasisveikinimas_3.setObjectName("pasisveikinimas_3")
        self.zinute = QtWidgets.QLabel(parent=self.centralwidget)
        self.zinute.setGeometry(QtCore.QRect(50, 320, 401, 61))
        self.zinute.setText("")
        self.zinute.setObjectName("zinute")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mygtukas.setText(_translate("MainWindow", "Įvesti"))
        self.pasisveikinimas.setText(_translate("MainWindow", "Įveskite vardą:"))
        self.pasisveikinimas_2.setText(_translate("MainWindow", "Įveskite pavadrę:"))
        self.pasisveikinimas_3.setText(_translate("MainWindow", "Įveskite gimimo metus:"))
